### ISSUE TITLE
signatures for POST, PATCH and PUT with query args

### ISSUE THREAD

**Issue by braydonf** [storj/service-middleware#2]
If query args are ever used with `POST`, `PATCH`, `PUT` the query args could be changed and the signature would still be valid.

https://github.com/Storj/service-middleware/blob/master/lib/authenticate.js#L170

**Comment by braydonf** [comment]
Using something similar to this should get all of the data for all http methods:
```js
var url = req.protocol + '://' + req.get('host') + req.originalUrl;
var hash = sha256(req.method, url, rawBody, nonce);
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
