### ISSUE TITLE
Authentication only one way, makes sense for trusted servers but not P2P

### ISSUE THREAD

**Issue by F483** [storj/service-middleware#8]
As infrastructure expands it should behave more like a P2P interface instead of a traditional server, this means it cannot be trusted and should sign responses so clients can confirm authenticity.

**Comment by F483** [comment]
With the micropayment hub I require two way authentication because there are two payment channels, one from the client to the hub and the reverse. Key is that everything (api calls and blockchain transactions) all use the same keys, so authentication as always clear in both regards.

https://github.com/F483/picopayments/blob/master/docs/api.md#mph_sync

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
